### ISSUE TITLE
100% width

### ISSUE THREAD

**Issue by louisebennett** [KingsOnline/adapt-h5p#1]
Would this break if we changed it to an automatic 100% width, instead of setting that manually? We'd still have to set the height, I know, but I think this would look better in different resolutions if we knew it would always fill the space available, width-wise.

**Comment by simondate** [comment]
I dunno why we didn't think of this 😆 Maybe it doesn't resize iframes? I'll try it now on my PC.

**Comment by simondate** [comment]
100% seems to work fine! Shall I get rid of the options and have it hard-coded to 100%?

**Comment by louisebennett** [comment]
AWESOME. Yes, let's do that - I can't imagine any circumstances in which we would specifically need it to be less than 100%.

**Comment by simondate** [comment]
If we do ever want it to be smaller we can just do it on a case by case basis using CSS

**Comment by louisebennett** [comment]
Yes, of course. Perfect!

**Comment by simondate** [comment]
Fixed in bf18525cfb9642486a7fb1947ed9ae4297dc553a
